#import <Foundation/Foundation.h>
#import "LTNGetHealth429Response.h"
#import "LTNGetV1RunnerModels200Response.h"
#import "LTNPostV1RunnerChat200Response.h"
#import "LTNPostV1RunnerChatRequest.h"
#import "LTNPostV1RunnerGenerateRequest.h"
#import "LTNApi.h"

/**
* lthn API
* Lethean Desktop HTTP gateway — same surface the WebView reaches via Wails bindings, exposed to external clients and the plugin market.
*
* The version of the OpenAPI document: 0.1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/



@interface LTNRunnerApi: NSObject <LTNApi>

extern NSString* kLTNRunnerApiErrorDomain;
extern NSInteger kLTNRunnerApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(LTNApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// List configured runner model routes
/// 
///
/// 
///  code:200 message:"Successful response",
///  code:400 message:"Bad request",
///  code:401 message:"Unauthorised",
///  code:403 message:"Forbidden",
///  code:429 message:"Too many requests",
///  code:500 message:"Internal server error",
///  code:504 message:"Gateway timeout"
///
/// @return LTNGetV1RunnerModels200Response*
-(NSURLSessionTask*) getV1RunnerModelsWithCompletionHandler: 
    (void (^)(LTNGetV1RunnerModels200Response* output, NSError* error)) handler;


/// Multi-turn chat completion
/// 
///
/// @param postV1RunnerChatRequest 
/// 
///  code:200 message:"Successful response",
///  code:400 message:"Bad request",
///  code:401 message:"Unauthorised",
///  code:403 message:"Forbidden",
///  code:429 message:"Too many requests",
///  code:500 message:"Internal server error",
///  code:504 message:"Gateway timeout"
///
/// @return LTNPostV1RunnerChat200Response*
-(NSURLSessionTask*) postV1RunnerChatWithPostV1RunnerChatRequest: (LTNPostV1RunnerChatRequest*) postV1RunnerChatRequest
    completionHandler: (void (^)(LTNPostV1RunnerChat200Response* output, NSError* error)) handler;


/// Single-prompt generation
/// 
///
/// @param postV1RunnerGenerateRequest 
/// 
///  code:200 message:"Successful response",
///  code:400 message:"Bad request",
///  code:401 message:"Unauthorised",
///  code:403 message:"Forbidden",
///  code:429 message:"Too many requests",
///  code:500 message:"Internal server error",
///  code:504 message:"Gateway timeout"
///
/// @return LTNPostV1RunnerChat200Response*
-(NSURLSessionTask*) postV1RunnerGenerateWithPostV1RunnerGenerateRequest: (LTNPostV1RunnerGenerateRequest*) postV1RunnerGenerateRequest
    completionHandler: (void (^)(LTNPostV1RunnerChat200Response* output, NSError* error)) handler;



@end
