#import <Foundation/Foundation.h>
#import "LTNGetHealth200Response.h"
#import "LTNGetHealth429Response.h"
#import "LTNApi.h"

/**
* lthn API
* Lethean Desktop HTTP gateway — same surface the WebView reaches via Wails bindings, exposed to external clients and the plugin market.
*
* The version of the OpenAPI document: 0.1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/



@interface LTNSystemApi: NSObject <LTNApi>

extern NSString* kLTNSystemApiErrorDomain;
extern NSInteger kLTNSystemApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(LTNApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Health check
/// Returns server health status
///
/// 
///  code:200 message:"Server is healthy",
///  code:429 message:"Too many requests",
///  code:500 message:"Internal server error",
///  code:504 message:"Gateway timeout"
///
/// @return LTNGetHealth200Response*
-(NSURLSessionTask*) getHealthWithCompletionHandler: 
    (void (^)(LTNGetHealth200Response* output, NSError* error)) handler;



@end
