#import <Foundation/Foundation.h>
#import "LTNObject.h"

/**
* lthn API
* Lethean Desktop HTTP gateway — same surface the WebView reaches via Wails bindings, exposed to external clients and the plugin market.
*
* The version of the OpenAPI document: 0.1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "LTNAnyType.h"
@protocol LTNAnyType;
@class LTNAnyType;



@protocol LTNError
@end

@interface LTNError : LTNObject


@property(nonatomic) NSString* code;

@property(nonatomic) LTNAnyType* details;

@property(nonatomic) NSString* message;

@end
