#import <Foundation/Foundation.h>
#import "LTNObject.h"

/**
* lthn API
* Lethean Desktop HTTP gateway — same surface the WebView reaches via Wails bindings, exposed to external clients and the plugin market.
*
* The version of the OpenAPI document: 0.1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "LTNError.h"
#import "LTNGetV1RunnerModels200ResponseData.h"
#import "LTNMeta.h"
@protocol LTNError;
@class LTNError;
@protocol LTNGetV1RunnerModels200ResponseData;
@class LTNGetV1RunnerModels200ResponseData;
@protocol LTNMeta;
@class LTNMeta;



@protocol LTNGetV1RunnerModels200Response
@end

@interface LTNGetV1RunnerModels200Response : LTNObject


@property(nonatomic) LTNGetV1RunnerModels200ResponseData* data;

@property(nonatomic) LTNError* error;

@property(nonatomic) LTNMeta* meta;

@property(nonatomic) NSNumber* success;

@end
