#import <Foundation/Foundation.h>
#import "LTNObject.h"

/**
* lthn API
* Lethean Desktop HTTP gateway — same surface the WebView reaches via Wails bindings, exposed to external clients and the plugin market.
*
* The version of the OpenAPI document: 0.1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "LTNPostV1RunnerChatRequestMessagesInner.h"
@protocol LTNPostV1RunnerChatRequestMessagesInner;
@class LTNPostV1RunnerChatRequestMessagesInner;



@protocol LTNPostV1RunnerChatRequest
@end

@interface LTNPostV1RunnerChatRequest : LTNObject


@property(nonatomic) NSArray<LTNPostV1RunnerChatRequestMessagesInner>* messages;

@end
