#import <Foundation/Foundation.h>
#import "LTNObject.h"

/**
* lthn API
* Lethean Desktop HTTP gateway — same surface the WebView reaches via Wails bindings, exposed to external clients and the plugin market.
*
* The version of the OpenAPI document: 0.1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "LTNAnyType.h"
#import "LTNError.h"
#import "LTNMeta.h"
@protocol LTNAnyType;
@class LTNAnyType;
@protocol LTNError;
@class LTNError;
@protocol LTNMeta;
@class LTNMeta;



@protocol LTNResponse
@end

@interface LTNResponse : LTNObject


@property(nonatomic) LTNAnyType* data;

@property(nonatomic) LTNError* error;

@property(nonatomic) LTNMeta* meta;

@property(nonatomic) NSNumber* success;

@end
